# -*- coding: utf-8 -*-
"""Assignment-5-CNN_cifar-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LROXtIFupSO8aVJnGhgjczqPZKJaavW1
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Flatten, Conv2D, MaxPooling2D, Dropout
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# Data Processing
(x_train, y_train), (x_temp, y_temp) = cifar10.load_data()

# test val split
x_test, x_val, y_test, y_val = train_test_split(x_temp, y_temp, test_size=0.3)

# Normalization
x_train = x_train / 255.0
x_test = x_test / 255.0
x_val = x_val / 255.0

# one hot method
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
y_val = to_categorical(y_val, 10)

# Model Build
model = Sequential()

model.add(Conv2D(8,(3,3), activation='relu', input_shape=(32,32,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(16, (3,3), activation='relu',))
model.add(MaxPooling2D(2,2))

model.add(Flatten())
model.add(Dense(8, activation='relu'))
model.add(Dense(10, activation='softmax'))

# Compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# model test
history = model.fit(x_train, y_train, epochs=5, validation_data=(x_val, y_val))

# print(x_train.shape)
# print(y_train.shape)
# print(x_test.shape)
# print(y_test.shape)
# print(x_val.shape)
# print(y_val.shape)

# evaluation
loss, accuracy = model.evaluate(x_test, y_test)
print("Total loss: ", loss)
print("Total accuracy: ", accuracy)

# prediction
#y_pred = model.predict(x_test)

# Ploting history
#plt.figure(figsize=(12,8))
plt.plot(history.history['loss'], label='Training Loss', color='green')
plt.plot(history.history['val_loss'], label='Validation Loss', color='red')
plt.title("Model Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

#plt.figure(figsize=(12,8))
plt.plot(history.history['accuracy'], label='Training Accuracy', color='green')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='red')
plt.title("Model Validation")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# Ploting image
class_names = [
    "Airplane",
    "Automobile",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Ship",
    "Truck"
]

predictions = model.predict(x_test)
y_pred = np.argmax(predictions, axis=1)
y_true = np.argmax(y_test, axis=1)

plt.figure(figsize=(12,8))
for i in range(10):
  plt.subplot(2,5,i+1)
  plt.imshow(x_test[i])
  plt.title(f"P:{class_names[y_pred[i]]}, T:{class_names[y_true[i]]}")
  plt.axis('off')
plt.tight_layout()
plt.show()

# Ploting just wrong prediction image
plt.figure(figsize=(12,8))

wrong = np.where(y_pred != y_true)[0]

for i in range(10):
  index = wrong[i]
  plt.subplot(2,5,i+1)
  plt.imshow(x_test[index])
  plt.title(f"P:{class_names[y_pred[index]]}, T:{class_names[y_true[index]]}")
  plt.axis('off')
plt.tight_layout
plt.show()