# -*- coding: utf-8 -*-
"""Assignment-8-VGG16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cgPzIeOe9czdFduRMOGu5_WyrteUaAx
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Flatten, Conv2D, MaxPooling2D , Dropout

# Build Model
model = Sequential()
model.add(Conv2D(64, (3,3),padding='same', activation='relu', input_shape=(224,224,3)))
model.add(Conv2D(64, (3,3), padding='same', activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(128,(3,3), padding='same', activation='relu'))
model.add(Conv2D(128,(3,3), padding='same', activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(256,(3,3), padding='same', activation='relu'))
model.add(Conv2D(256,(3,3), padding='same', activation='relu'))
model.add(Conv2D(256,(3,3), padding='same', activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(512,(3,3), padding='same', activation='relu'))
model.add(Conv2D(512,(3,3), padding='same', activation='relu'))
model.add(Conv2D(512,(3,3), padding='same', activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(512,(3,3), padding='same', activation='relu'))
model.add(Conv2D(512,(3,3), padding='same', activation='relu'))
model.add(Conv2D(512,(3,3), padding='same', activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1000, activation='softmax'))

model.summary()