# -*- coding: utf-8 -*-
"""Assignment-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZz71E_sUAPZXgp109QHVam3II1xPjVH
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.layers import Input, Dense, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Data Processing

# data load
(x_train , y_train) , (x_temp, y_temp) = fashion_mnist.load_data()

# split validation
x_test, x_val, y_test, y_val = train_test_split(x_temp, y_temp, test_size=0.3, random_state=42)

# normalize
x_train = x_train /255.0
x_test = x_test/ 255.0
x_val = x_val/ 255.0
#One hot apply
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
y_val = to_categorical(y_val, 10)

# Model build
model = Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(10, activation='softmax'))

# model compile
model.compile(optimizer='adam', loss ='categorical_crossentropy', metrics=['accuracy'])

# Model train
history = model.fit(x_train, y_train, epochs=10, validation_data=(x_val, y_val),verbose=1)

print(history.history.keys())
# model evaluation
loss, accuracy = model.evaluate(x_test, y_test)
print("Total Loss: ", loss)
print("Total Accuracy: ", accuracy)

# model prediction
y_pred = model.predict(x_test)

# plot accuracy
plt.plot(history.history['accuracy'], label="Accuracy", color='green')
plt.plot(history.history['val_accuracy'], label="Val-Accuracy", color='red')
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# plot loss
plt.plot(history.history['loss'], label = 'Loss', color = 'green')
plt.plot(history.history['val_loss'], label = "Val-Loss", color = 'red')
plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_val.shape)
print(y_val.shape)

# plot history
import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'], label = 'Accuracy', color = 'green')
plt.plot(history.history['val_accuracy'], label = "Val-Accuracy", color = 'red')
plt.title("Model Accuracy")
plt.legend()
plt.show()

plt.plot(history.history['loss'], label = 'Loss', color = 'green')
plt.plot(history.history['val_loss'], label = "Val-Loss", color = 'red')
plt.title("Model Accuracy")
plt.legend()
plt.show()

# prediction and true image visualization
# for fashion_mnist
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
predictions = model.predict(x_test)
y_pred = np.argmax(predictions, axis=1)
y_true = np.argmax(y_test, axis = 1)

plt.figure(figsize=(12,8))
for i in range(25):
  plt.subplot(5,5,i+1)
  plt.imshow(x_test[i], cmap='gray')
  # For fashion_mnist
  plt.title(f"predict:{class_names[y_pred[i]]}, True:{class_names[y_true[i]]}")
  # for mnist
  #   plt.title(f"predict:{y_pred[i]}, True:{y_true[i]}")
  plt.axis('off')
plt.tight_layout()
plt.show()

# Only wrong output visualization

plt.figure(figsize=(10,5))
wrong = np.where(y_pred !=y_true)[0]
for i in range(10):
  plt.subplot(2,5,i+1)
  index = wrong[i]
  plt.imshow(x_test[index], cmap='gray')
  plt.title(f"P:{class_names[y_pred[index]]} T:{class_names[y_true[index]]}")
  # plt.title(f"Predict:{y_pred[index]} Ture:{y_true[index]}")
  plt.axis('off')
plt.tight_layout()
plt.show()

