# -*- coding: utf-8 -*-
"""Assignment-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TC3hO553XrA2zSyiEVipWjGZx716hE6M
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Data Processing

# Random x genrate
x = np.linspace(-10, 10, 50000)
x = x.reshape(-1,1)

# y genearate
y1 = 5 * x + 10
y2 = 3*x**2 + 5*x + 10
y3 = 4*x**3 + 3*x**2 + 5*x + 10

# Train, test , val data split
def split(x, y):
  x_train , x_temp , y_train, y_temp = train_test_split(x, y, test_size=0.3, random_state= 42)
  x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size = 0.5, random_state =42)
  return x_train, y_train, x_test, y_test, x_val, y_val

x_train, y_train, x_test, y_test, x_val, y_val = split(x, y1)

#  Model Design
model = Sequential()
model.add(Dense(8, activation='relu',))
model.add(Dense(1,))

# Model Compile
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Model test
history = model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=5, verbose=1)

# Testing
loss, mae = model.evaluate(x_test, y_test)
print("Loss : ", loss)
print("MAE: ", mae)


y_pred = model.predict(x_test)

r2 = r2_score(y_test, y_pred)
print("R2 Score: ", r2)
print("Training History: ", history.history.keys())

# Plot predictions vs orginal
plt.figure(figsize=(10,6))
plt.plot(x_test, y_test, label="Origianl y", color = 'green')
plt.plot(x_test,y_pred, label= "predicted y", color = 'red')
plt.legend()
plt.title("First Equation")
plt.show()

# plt.figure(figsize=(10,6))
# plt.scatter(x_test, y_test, label="Origianl y", color = 'green')
# plt.plot(x_test,y_pred, label= "predicted y", color = 'red')
# plt.legend()
# plt.title("Second Equation")
# plt.show()

# plot training history
plt.plot(history.history['loss'], label = 'Training Loss')
plt.plot(history.history['val_loss'], label = 'Validation Loss')
plt.title("Traing loss for equation 1")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

# plot training history
plt.plot(history.history['mae'], label = 'Training mae')
plt.plot(history.history['val_mae'], label = 'Validation mae')
plt.title("Traing mae for equation 1")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

